'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {Dice5,Users,Copy,Check,ArrowRight,BookOpen,RotateCcw,LogOut,Coins,Eye,X} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {judge,maxBet,Room,validBetLimit,cycleLocked,remainingDealers} from '@/lib/game';
import RoomChat from '@/components/room-chat';
import FinalSettlement from '@/components/final-settlement';
import TableEffects,{Dice} from '@/components/table-effects';
type Session={code:string;token:string;me:string};
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>}
function BetLimitInput({value,onChange}:{value:string;onChange:(s:string)=>void}){return <><label htmlFor="bet-limit">1回の賭け金上限</label><input id="bet-limit" type="number" inputMode="numeric" min={1} step={1} placeholder="空欄で上限なし" value={value} onChange={e=>onChange(e.target.value)}/><small className="hint">空欄：上限なし。指定する場合は1以上の整数。</small></>}
function Rules(){return <Dialog><DialogTrigger asChild><button className="quiet"><BookOpen size={17}/> ルール</button></DialogTrigger><DialogContent className="rules"><DialogTitle>この卓のルール</DialogTitle><DialogDescription>架空のチップで遊ぶ、親との役比べです。</DialogDescription><div className="rule-list">{[['ピンゾロ','1・1・1','5倍'],['ゾロ目','同じ数字が3つ（1以外）','3倍'],['シゴロ','4・5・6','2倍'],['6〜1の目','同じ数字2つ＋残り1つの数字','1倍'],['役なし','組み合わせなし','1倍'],['ヒフミ','1・2・3','2倍負け']].map(([n,d,m])=><div key={n}><strong>{n}</strong><span>{d}</span><b>{m}</b></div>)}</div><p>上にある役ほど強く、ゾロ目同士は同点。全員が振った後に各子と親を比較し、同じ強さなら引き分けです。</p><p>役が出たら自動確定。役なしのときだけ、設定回数まで3個とも振り直せます。最初の1投は振り直し回数に含みません。</p><p>精算額は賭け金 × 勝者の役の倍率。敗者がヒフミなら、さらに2倍を掛け合わせます（ピンゾロ10倍・ゾロ目6倍・シゴロ4倍）。同じ強さの役は引き分けで、チップの移動はありません。ションベンや親の即勝ち・即負けはありません。</p><p>賭け金は「自分の持ちチップ」と「ルームの1回の賭け金上限」の小さい方まで。上限なしの場合は持ちチップ全額まで。賭け上限は最初と親一周の終了後だけ変更でき、途中で待合室に戻っても固定されます。プレイヤー参加・観戦への切り替え・退出は周の区切りで行います。自分で観戦へ切り替えるほか、ホストも参加者を観戦へ移せます。それまでの収支は清算に残り、プレイヤーへ戻る場合も残高を引き継ぎます。対戦中や満席でも観戦でき、観戦者はいつでも退出できます。親の残高による制限はなく、倍率で負けた分は残高がマイナスになっても全額精算します。誰かの残高が0以下になったら、その局の結果確定後に自動で清算へ進みます。全員の残高がプラスでも、ホストはいつでも対戦を終了して清算できます。対戦が続く間、親は1局ごとに交代します。</p><p>途中で接続が切れても同じタブを再読み込みすると復帰できます。進行できない場合はホストが待合室に戻せます。未精算の局は取り消され、ルームは作成から24時間で期限切れになります。</p></DialogContent></Dialog>}
export default function Home(){
 const mutation=useRef(0),acting=useRef(false);
 const [room,setRoom]=useState<Room|null>(null),[session,setSession]=useState<Session|null>(null),[name,setName]=useState(''),[code,setCode]=useState(''),[rerolls,setRerolls]=useState('2'),[initial,setInitial]=useState('3000'),[betLimit,setBetLimit]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[bet,setBet]=useState('100'),[copied,setCopied]=useState(false),[rolling,setRolling]=useState(false),[online,setOnline]=useState(true),[mode,setMode]=useState<'create'|'join'>('create');
 const parsedBetLimit=betLimit.trim()===''?null:Number(betLimit);const betLimitValid=validBetLimit(parsedBetLimit);
 useEffect(()=>{if(room)setBetLimit(room.betLimit==null?'':String(room.betLimit))},[room?.code,room?.betLimit]);
 useEffect(()=>{const c=new URLSearchParams(location.search).get('room');if(c){setCode(c.toUpperCase());setMode('join')}try{const s=JSON.parse(sessionStorage.getItem('chinchiro-session')||'null');if(s&&(!c||s.code===c.toUpperCase()))setSession(s);setName(localStorage.getItem('chinchiro-name')||'')}catch{}},[]);
 const refresh=useCallback(async()=>{if(!session||acting.current)return;const epoch=mutation.current;try{const res=await fetch(`/api/game?code=${session.code}`,{headers:{Authorization:`Bearer ${session.token}`}});const data=await res.json() as {room:Room;error:string};if(acting.current||epoch!==mutation.current)return;if(!res.ok){if(res.status===401||res.status===404){setSession(null);setRoom(null);sessionStorage.removeItem('chinchiro-session');setError(data.error)}else setOnline(false);return}setRoom(data.room);setOnline(true)}catch{setOnline(false)}},[session]);
 useEffect(()=>{refresh();const t=setInterval(refresh,1800);return()=>clearInterval(t)},[refresh]);
 async function act(action:string,extra:Record<string,unknown>={}){if(acting.current)return;acting.current=true;mutation.current++;setBusy(true);setError('');if(action==='roll')setRolling(true);try{const res=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json',...(session?{Authorization:`Bearer ${session.token}`}:{})},body:JSON.stringify({action,code:session?.code||code.trim().toUpperCase(),name,rerolls:Number(rerolls),initial:Number(initial),betLimit:parsedBetLimit,...extra})});const d=await res.json() as {room:Room;token?:string;me:string;error:string};if(!res.ok)throw Error(d.error);if(action==='leave'){setSession(null);setRoom(null);sessionStorage.removeItem('chinchiro-session');history.replaceState(null,'',location.pathname);return}if(d.token){const s={code:d.room.code,token:d.token,me:d.me};setSession(s);sessionStorage.setItem('chinchiro-session',JSON.stringify(s));localStorage.setItem('chinchiro-name',name);history.replaceState(null,'',`?room=${s.code}`)}if(action==='roll')await new Promise(r=>setTimeout(r,1050));setRoom(d.room);setOnline(true);return true}catch(e){setError(e instanceof Error?e.message:'通信に失敗しました')}finally{acting.current=false;setBusy(false);setRolling(false)}}
 async function copy(){if(!room)return;try{await navigator.clipboard.writeText(`${location.origin}/?room=${room.code}`);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError(`招待コード：${room.code} を友達に伝えてください`)}}
 const capLocked=room?cycleLocked(room):false;
 const me=room?.players.find(p=>p.id===session?.me),host=room?.host===me?.id,ownTurn=room?.phase==='rolling'&&room.players[room.turn]?.id===me?.id;
 const spectator=room?.spectators?.find(p=>p.id===session?.me);
 const spectating=!!spectator;
 const canTakeSeat=!!room&&!capLocked&&['lobby','result'].includes(room.phase)&&room.players.length<8;
 const current=room?.phase==='rolling'?room.players[room.turn]:me;const limit=room&&me?maxBet(room,me):0;
 const steps=['参加','チップを賭ける','サイコロを振る',room?.phase==='settlement'?'清算':'結果'];const step=!room||room.phase==='lobby'?0:room.phase==='betting'?1:room.phase==='rolling'?2:3;
 return <div className={`app-shell phase-${room?.phase||'setup'} ${ownTurn?'your-turn':''}`}><header><a href="/" className="brand"><span className="brand-icon"><Dice5 size={25}/></span><span>チンチロ <b>卓</b><small>CHINCHIRO CLUB</small></span></a><div className="header-right"><span className="virtual">架空チップで遊ぼう</span><Rules/></div></header><main><div className="title-row"><div><div className="eyebrow">CHINCHIRO / HIGH SPIRITS</div><h1>{room?.phase==='settlement'?'全員の収支を、ひと目で。':room?'さあ、勝負の時間。':'一投に、勝負を。'}</h1><p>{room?`第 ${room.round||1} 局 · 振り直し ${room.rerolls} 回まで · 賭け上限 ${room.betLimit==null?'なし':room.betLimit.toLocaleString()+' チップ'}`:'友達と囲む、オンラインのチンチロ卓。'}</p></div><div className="room-tag">{room?<><span>ROOM</span><b>{room.code}</b><button aria-label="招待リンクをコピー" onClick={copy}>{copied?<Check size={18}/>:<Copy size={18}/>}</button></>:<><Users size={18}/><b>2 — 8 PLAYERS</b></>}</div></div>
 <nav className="steps" aria-label="進行状況">{steps.map((s,i)=><div key={s} className={step===i?'active':step>i?'passed':''}><span>{step>i?'✓':`0${i+1}`}</span>{s}</div>)}</nav>
 {error&&<div className="notice" role="alert">{error}<button aria-label="閉じる" onClick={()=>setError('')}><X size={17}/></button></div>}{!online&&<div className="notice">再接続中です。通信が戻るまでお待ちください。</div>}
 {spectating&&room&&<div className="spectator-banner"><div><strong>観戦モード</strong><p>{canTakeSeat?'空席があります。プレイヤーとして参加できます。':room.players.length>=8?'現在は満席です。空席ができるまで観戦できます。':room.phase==='settlement'?'清算を観戦中。次の対戦の待合室で参加できます。':'親一周の終了後にプレイヤーとして参加できます。'} {spectator?.chips!==undefined?`観戦へ移る前の残高 ${spectator.chips.toLocaleString()} チップは清算に残ります。`:'チップの増減はありません。'}</p></div><div className="spectator-actions">{canTakeSeat&&<button className="primary" disabled={busy||!online} onClick={()=>act('take_seat')}>プレイヤーとして参加</button>}<button className="secondary" disabled={busy} onClick={()=>act('leave')}><LogOut size={16}/> 観戦を退出</button></div></div>}
 {room?.phase==='settlement'?<FinalSettlement room={room} meId={session?.me} host={host} busy={busy} onRestart={()=>{if(confirm('清算を終えますか？ 全員のチップと対戦結果がリセットされます。'))act('restart')}}/>:<div className={`game-layout ${!room?'setup':''}`}><section className="table-area"><div className="table-heading"><span><i/> {room?room.phase==='lobby'?'WAITING ROOM':room.phase==='result'?'ROUND COMPLETE':'LIVE TABLE':'YOUR NEXT GAME'}</span><span className="round-badge">{room?`ROUND ${String(room.round||1).padStart(2,'0')}`:'ONLINE · 2–8 PLAYERS'}</span></div><div className={`felt ${rolling?'rolling':''}`}><div className="felt-inner"><div className="table-mark"><span className="table-kanji">勝 負</span>CHINCHIRO</div><TableEffects room={room} meId={session?.me} rolling={rolling}/><div className="table-message" aria-live="polite"><div className="table-kicker">{!room?'LET’S ROLL':room.phase==='lobby'?'みんなが集まるのを待っています':room.phase==='betting'?'BETTING TIME':room.phase==='result'?(spectating?'ROUND RESULT':'YOUR RESULT'):`${current?.name} の番`}</div><h2>{rolling?'ころころ…':!room?'運も、勝負も、ここから。':room.phase==='lobby'?`${room.players.length} 人が着席中`:room.phase==='betting'?(spectating?'賭けチップの確定を待っています':'チップを賭けよう'):room.phase==='result'?spectating?'この局の結果が出ました':`${me?.delta&&me.delta>0?'+':''}${me?.delta.toLocaleString()} チップ`:current?.dice.length?judge(current.dice).name:'サイコロを振ろう'}</h2><p>{!room?'ルームを作って、友達を招待。':room.phase==='lobby'?'招待リンクかルームコードを友達に送ろう。':room.phase==='betting'?`${room.players.filter(p=>p.ready).length} / ${room.players.length} 人 準備完了`:room.phase==='rolling'?`投数 ${current?.rolls||0} / ${room.rerolls+1} · ${ownTurn?'あなたの番です':'相手の操作を待っています'}`:'この局のチップを精算しました。'}</p></div>
 {ownTurn&&<div className="roll-actions"><button className="primary" disabled={busy||!online} onClick={()=>act('roll')}><Dice5 size={20}/>{me?.rolls?'もう一度振る':'サイコロを振る'}</button>{!!me?.rolls&&<button className="felt-button" disabled={busy} onClick={()=>act('hold')}>役なしで確定</button>}</div>}
 {room?.phase==='result'&&host&&<button className="primary" disabled={busy||(!capLocked&&parsedBetLimit!==(room.betLimit??null))} onClick={()=>act('next')}>{capLocked?'次の局へ':'次の一周をはじめる'} <ArrowRight size={18}/></button>}
 </div></div><div className="table-footer"><span><Coins size={16}/> 換金なし・ゲーム内チップのみ</span><span>役の判定・精算は自動</span></div></section>
 <aside className="sidebar">{!room?<><div className="panel"><div className="panel-title"><span className="number">01</span><h2>卓につく</h2></div><label htmlFor="player-name">あなたの名前</label><input id="player-name" placeholder="例：さいころ太郎" maxLength={16} value={name} onChange={e=>setName(e.target.value)}/><div className="mode-buttons"><button className={mode==='create'?'selected':''} onClick={()=>setMode('create')}>ルームを作成</button><button className={mode==='join'?'selected':''} onClick={()=>setMode('join')}>ルームに参加</button></div>{mode==='create'?<><label>振り直し回数</label><Choice label="振り直し回数" value={rerolls} onChange={setRerolls} options={Array.from({length:6},(_,i)=>[String(i),`${i} 回${i===2?'（通常）':''}`])}/><small className="hint">最初の1投 ＋ 設定した回数</small><label>最初の持ちチップ</label><Choice label="最初の持ちチップ" value={initial} onChange={setInitial} options={['1000','3000','10000'].map(n=>[n,Number(n).toLocaleString()+' チップ'])}/><BetLimitInput value={betLimit} onChange={setBetLimit}/><button className="primary wide" disabled={busy||!name.trim()||!betLimitValid} onClick={()=>act('create')}>{busy?'作成中…':'ルームを作る'} <ArrowRight size={18}/></button></>:<><label htmlFor="room-code">ルームコード</label><input id="room-code" className="code-input" placeholder="8桁のコード" maxLength={8} value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''))}/><button className="primary wide" disabled={busy||!name.trim()||code.length!==8} onClick={()=>act('join')}>{busy?'参加中…':'この卓に参加する'} <ArrowRight size={18}/></button></>}</div><div className="tip"><span>役が出たら、自動で勝負。</span><p>役は自動で判定。チップの計算もおまかせ。あなたはサイコロを振るだけ。</p></div></>:<>
 {!spectating&&<div className={`panel balance ${(me?.chips??0)<0?'balance-negative':''}`}><span>YOUR STACK <small>あなたの持ちチップ</small></span><strong><Coins size={23}/>{me?.chips.toLocaleString()}<small>CHIPS</small></strong></div>}
 {room&&<div className="panel"><h2>この一周の賭け上限：{room.betLimit==null?'なし':room.betLimit.toLocaleString()+' チップ'}</h2>{capLocked?<p>親一周まで残り {remainingDealers(room).length} 人。この一周が終わるまで変更できません。</p>:<><p>{room.round>0?'親が一周しました。次の一周の上限をみんなで相談してください。':'最初の一周の上限をみんなで相談してください。'}</p>{host?<><BetLimitInput value={betLimit} onChange={setBetLimit}/><button className="secondary wide" disabled={busy||!betLimitValid||parsedBetLimit===(room.betLimit??null)} onClick={()=>act('settings')}>上限を保存</button>{parsedBetLimit!==(room.betLimit??null)&&<small className="hint">変更を保存してから次へ進んでください。</small>}</>:<p>ホストが上限を設定できます。</p>}</>}</div>}
 {room.phase==='lobby'?<div className="panel"><h2>友達を招待</h2><button className="secondary wide" onClick={copy}>{copied?<Check size={18}/>:<Copy size={18}/>} {copied?'コピーしました':'招待リンクをコピー'}</button><p className="hint">コード：{room.code}<br/>2〜8人で開始できます。</p>{host?<><button className="primary wide" disabled={busy||room.players.length<2||(!capLocked&&parsedBetLimit!==(room.betLimit??null))} onClick={()=>act('start')}>対戦をはじめる <ArrowRight size={18}/></button>{parsedBetLimit!==(room.betLimit??null)&&<small className="hint">変更した上限を保存してから開始してください。</small>}</>:<p>ホストの開始を待っています。</p>}</div>:room.phase==='betting'&&spectating?<div className="panel"><h2>賭けを受付中</h2><p>全員の準備ができたら、サイコロの勝負が始まります。</p></div>:room.phase==='betting'?<div className="panel"><h2>{room.players[room.dealer].id===me?.id?'あなたが親です':me?.ready?(me.bet===0?'今回は見学':'賭けチップ確定'):'今回の賭けチップ'}</h2>{me?.ready?<p>{room.players[room.dealer].id===me.id?'全員の賭けが揃ったら、最初に振ります。':me.bet===0?'残高が0以下のため、今回は賭けずに観戦します。':`${me.bet.toLocaleString()} チップで勝負。全員の準備を待っています。`}</p>:<><label htmlFor="bet">1 〜 {limit.toLocaleString()} チップ</label><input id="bet" type="number" min={1} max={limit} value={bet} onChange={e=>setBet(e.target.value)}/><div className="bet-presets">{[10,50,100].map(n=><button key={n} disabled={n>limit} onClick={()=>setBet(String(n))}>{n}</button>)}<button onClick={()=>setBet(String(limit))}>{limit===(me?.chips??0)?'全額':'上限'}</button></div><button className="primary wide" disabled={busy||!Number.isInteger(Number(bet))||Number(bet)<1||Number(bet)>limit} onClick={()=>act('bet',{bet:Number(bet)})}>このチップで勝負</button><small className="hint">ルーム上限と持ちチップの範囲で賭けられます。倍率負けで残高がマイナスになることがあります。</small></>}</div>:room.phase==='rolling'?<div className="panel"><h2>{ownTurn?'あなたの番です':'相手の番です'}</h2><p>{ownTurn?'役なしなら振り直しOK。役が出ると自動で確定します。':`${room.players[room.turn].name} がサイコロを振っています。`}</p></div>:<div className="panel"><h2>第 {room.round} 局の精算</h2>{room.players.map(p=><div className="settlement" key={p.id}><span>{p.name}</span><b className={p.delta>0?'gain':p.delta<0?'loss':''}>{p.delta>0?'+':''}{p.delta.toLocaleString()}</b></div>)}</div>}
 <div className="panel players"><div className="section-label"><h2>この卓のメンバー</h2><span>{room.players.length} / 8</span></div>{room.players.map((p,i)=><div className={`player ${room.phase==='rolling'&&room.turn===i?'is-turn':''}`} key={p.id}><span className="avatar">{p.name.slice(0,1)}</span><div className="player-info"><strong>{p.name}{p.id===me?.id&&<small>あなた</small>}{i===room.dealer&&<em>親</em>}</strong><span>{p.chips.toLocaleString()} chips{p.bet>0?` · 賭け ${p.bet}`:room.phase!=='lobby'&&i!==room.dealer&&p.chips<=0?' · 見学':''}</span>{p.dice.length===3&&<div className={`player-role ${p.done?'confirmed':'pending'}`}><b>{judge(p.dice).name}</b><small>{p.done?'確定':'振り直し可'}</small></div>}</div>{room.phase==='betting'&&p.ready&&<Check size={18}/ >}{host&&p.id!==me?.id&&<button className="icon-button" disabled={busy||capLocked||!['lobby','result'].includes(room.phase)} title={capLocked?'親一周の終了後に観戦へ移せます':'観戦へ移す'} aria-label={`${p.name}を観戦へ移す`} onClick={()=>act('spectate',{id:p.id})}><Eye size={18}/></button>}</div>)}</div>
 {host&&<button className="secondary wide" disabled={busy} onClick={()=>{if(confirm('対戦を終了して清算しますか？ 進行中の未確定の局は取り消し、確定済みの結果で計算します。'))act('settlement')}}><Coins size={18}/> 対戦を終了して清算する</button>}
 {(room.spectators?.length??0)>0&&<div className="panel spectators"><div className="section-label"><h2>観戦中</h2><span>{room.spectators!.length} 人</span></div>{room.spectators!.map(p=><div className="player" key={p.id}><span className="avatar">{p.name.slice(0,1)}</span><strong>{p.name}{p.id===session?.me&&<small>（あなた）</small>}</strong></div>)}</div>}
 {!spectating&&<div className="panel"><button className="secondary wide" disabled={busy||capLocked||!['lobby','result'].includes(room.phase)||room.players.length<=1} onClick={()=>act('spectate')}><Eye size={17}/> 観戦に切り替える</button><small className="hint">{capLocked?'親一周の終了後に切り替えられます。':room.players.length<=1?'最後のプレイヤーは観戦へ移動できません。':'切り替えると待合室へ戻ります。今までの収支は清算に残ります。'}{host&&room.players.length>1?' ホストは次のプレイヤーへ引き継ぎます。':''}</small></div>}
 <div className="room-tools">{host&&room.phase!=='lobby'&&<button disabled={busy} onClick={()=>{if(confirm('待合室に戻りますか？ 未精算の局は取り消されます。賭け上限は親一周まで固定です。'))act('lobby')}}><RotateCcw size={15}/> 待合室に戻る</button>}{!spectating&&room.phase==='lobby'&&!capLocked&&<button disabled={busy} onClick={()=>act('leave')}><LogOut size={15}/> 退出</button>}</div>
 </>}</aside></div>}<section className="role-strip"><div className="role-title">役の早見表<small>強い順 →</small></div>{[['ピンゾロ','5倍','111'],['ゾロ目','3倍','333'],['シゴロ','2倍','456'],['通常の目','1倍','226'],['役なし','1倍','245'],['ヒフミ','2倍負け','123']].map(([n,m,d])=><div className="role-card" key={n}><div>{d.split('').map((v,i)=><Dice key={i} small value={Number(v)}/>)}</div><strong>{n}</strong><span>{m}</span></div>)}</section><footer><span>CHINCHIRO CLUB</span><span>気の合う仲間と、いい勝負を。</span></footer></main>{room&&<RoomChat key={room.code} messages={room.messages??[]} meId={session?.me} disabled={busy||!online} onSend={text=>act('chat',{text}).then(ok=>!!ok)} onReact={(messageId,emoji)=>act('react',{messageId,emoji}).then(ok=>!!ok)}/>}</div>
}
