'use client';
import {ArrowRight,Check,Coins,RotateCcw} from 'lucide-react';
import {Room,settlementTransfers,settlementParticipants} from '@/lib/game';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
export default function FinalSettlement({room,meId,host,busy,onRestart}:{room:Room;meId?:string;host:boolean;busy:boolean;onRestart:()=>void}){
 const {transfers,imbalance}=settlementTransfers(room);const participants=settlementParticipants(room);const me=participants.find(p=>p.id===meId);const diff=me?me.chips-room.initial:0;const name=(id:string)=>participants.find(p=>p.id===id)?.name||id;
 return <section className="final-settlement" aria-label="対戦全体の清算"><div className="settlement-hero"><div><span className="eyebrow">FINAL SETTLEMENT</span><h2>おつかれさま。清算の時間です。</h2><p>{room.settlementReason==='negative'?'残高が0以下になった人がいるため、対戦を終了しました。':'ホストが対戦を終了して、清算に進みました。'}</p>{room.cancelledRound&&<p>進行中だった局は取り消しました。確定済みの局だけで計算しています。</p>}</div>{me?<div className={`final-total ${diff>0?'positive':diff<0?'negative':''}`}><span>あなたの合計{diff>=0?'受け取り':'支払い'}</span><strong>{Math.abs(diff).toLocaleString()}<small> チップ</small></strong></div>:<div className="final-total"><span>観戦中</span><p>チップの受け渡しはありません</p></div>}</div>
 <div className="settlement-columns"><div className="panel"><h2><Coins size={20}/> 誰から、誰へ、何チップ？</h2><p>観戦へ移動した人・退出した人も含め、開始時の {room.initial.toLocaleString()} チップからの増減を相殺した受け渡し一覧です。各局の支払いを重ねて行う必要はありません。</p>{imbalance!==0?<div className="notice" role="alert">参加者の差額合計が一致しません（{imbalance.toLocaleString()} チップ）。過去の退出・リセットの影響が考えられるため、受け渡し額を確定できません。</div>:transfers.length===0?<div className="no-transfer"><Check size={28}/><strong>受け渡しはありません</strong><span>全員の収支が0チップです。</span></div>:<ol className="transfer-list">{transfers.map((t,i)=><li key={`${t.from}-${t.to}`} className={t.from===meId||t.to===meId?'your-transfer':''}><span className="transfer-index">{String(i+1).padStart(2,'0')}</span><div className="transfer-person"><small>渡す人</small><strong>{name(t.from)}{t.from===meId&&<em>あなた</em>}</strong></div><div className="transfer-amount"><b>{t.amount.toLocaleString()}</b><small>チップ</small><ArrowRight size={28}/></div><div className="transfer-person"><small>受け取る人</small><strong>{name(t.to)}{t.to===meId&&<em>あなた</em>}</strong></div></li>)}</ol>}<small className="hint">受け渡しの案内です。ここで表示した分がゲーム内残高からさらに引かれることはありません。</small></div>
 <div className="panel"><h2>みんなの最終収支</h2><Table><TableHeader><TableRow><TableHead>名前</TableHead><TableHead className="text-right">終了時</TableHead><TableHead className="text-right">差額</TableHead></TableRow></TableHeader><TableBody>{participants.map(p=>{const n=p.chips-room.initial;return <TableRow key={p.id}><TableCell className="settlement-name">{p.name}</TableCell><TableCell className="text-right">{p.chips.toLocaleString()}</TableCell><TableCell className={`text-right ${n>0?'gain':n<0?'loss':''}`}>{n>0?'+':''}{n.toLocaleString()}</TableCell></TableRow>})}</TableBody></Table><p>差額がプラスの人が受け取り、マイナスの人が支払います。残高のマイナス分だけではなく、開始時からの負け分全体です。</p>{host?<button disabled={busy} className="primary wide" onClick={onRestart}><RotateCcw size={18}/> 清算を終えて、新しい対戦へ</button>:<p>次の対戦はホストが開始できます。</p>}<small className="hint">新しい対戦では全員のチップを {room.initial.toLocaleString()} に戻し、親一周を最初から始めます。</small></div></div></section>
}
