'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,Send,X} from 'lucide-react';
import {CHAT_REACTIONS,type ChatMessage} from '@/lib/game';
import {SmilePlus} from 'lucide-react';
export default function RoomChat({messages,meId,disabled,onSend,onReact}:{messages:ChatMessage[];meId?:string;disabled:boolean;onSend:(text:string)=>Promise<boolean>;onReact:(messageId:string,emoji:string)=>Promise<boolean>}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState(''),[seen,setSeen]=useState<string|undefined>(messages.at(-1)?.id);
 const list=useRef<HTMLDivElement>(null),nearBottom=useRef(true),input=useRef<HTMLTextAreaElement>(null),pending=useRef(false);
 const latest=messages.at(-1)?.id,seenIndex=messages.findIndex(m=>m.id===seen),unread=messages.slice(seenIndex+1).filter(m=>m.senderId!==meId).length;
 useEffect(()=>{if(open){setSeen(latest);if(list.current&&nearBottom.current)list.current.scrollTop=list.current.scrollHeight}},[latest,open]);
 useEffect(()=>{if(open){nearBottom.current=true;if(list.current)list.current.scrollTop=list.current.scrollHeight;input.current?.focus()}},[open]);
 async function send(){const text=draft.trim();if(!text||disabled||pending.current)return;pending.current=true;setSending(true);setError('');try{if(await onSend(text)){setDraft('');nearBottom.current=true}else setError('送信できませんでした。本文は残っています。もう一度お試しください。')}catch{setError('通信できませんでした。もう一度お試しください。')}finally{pending.current=false;setSending(false)}}
 return <div className="room-chat">{open&&<section className="chat-panel" aria-label="ルームチャット"><div className="chat-heading"><div><strong>卓のチャット</strong><small>プレイヤーも観戦者もどうぞ</small></div><button aria-label="チャットを閉じる" onClick={()=>setOpen(false)}><X size={19}/></button></div><div ref={list} className="chat-messages" role="log" aria-label="メッセージ" aria-live="polite" aria-relevant="additions" onScroll={()=>{const el=list.current;if(el)nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<60}}>{messages.length===0?<p className="chat-empty">「よろしく！」から始めよう。<br/>このルームのみんなに届きます。</p>:messages.map(m=><article className={`chat-message ${m.senderId===meId?'mine':''}`} key={m.id}><div className="chat-meta"><strong>{m.name}</strong>{m.spectator&&<span>観戦</span>}<time dateTime={new Date(m.sentAt).toISOString()}>{new Date(m.sentAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</time></div><p>{m.text}</p><MessageReactions message={m} meId={meId} disabled={disabled} onReact={onReact}/></article>)}</div><form className="chat-compose" onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="chat-message" className="sr-only">メッセージ</label><textarea ref={input} id="chat-message" placeholder="メッセージを入力…" value={draft} maxLength={300} rows={2} disabled={sending} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.keyCode!==229){e.preventDefault();void send()}}}/><div className="chat-compose-footer"><small>{draft.length}/300 · 最新100件</small><button className="primary" type="submit" disabled={disabled||sending||!draft.trim()}><Send size={16}/>{sending?'送信中':'送信'}</button></div>{error&&<p className="chat-error" role="alert">{error}</p>}</form></section>}<button className="chat-launcher" aria-expanded={open} onClick={()=>setOpen(!open)}><MessageCircle size={20}/> チャット{!open&&unread>0&&<span className="chat-unread">{unread}</span>}</button></div>
}

export function MessageReactions({message,meId,disabled,onReact}:{message:ChatMessage;meId?:string;disabled:boolean;onReact:(messageId:string,emoji:string)=>Promise<boolean>}){
 const [expanded,setExpanded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const pending=useRef(false);
 const reactions=message.reactions??[],full=reactions.length>=5;
 async function react(emoji:string){if(disabled||pending.current)return;pending.current=true;setBusy(true);setError('');try{if(await onReact(message.id,emoji))setExpanded(false);else setError('変更できませんでした。もう一度お試しください。')}catch{setError('通信できませんでした。もう一度お試しください。')}finally{pending.current=false;setBusy(false)}}
 const buttons=CHAT_REACTIONS.map(emoji=>{const count=reactions.filter(r=>r.emoji===emoji).length,mine=reactions.some(r=>r.emoji===emoji&&r.userId===meId);return {emoji,count,mine}});
 return <div className="message-reactions" onKeyDown={e=>{if(e.key==='Escape')setExpanded(false)}}><div className={`reaction-row ${expanded?'picker-open':''}`} aria-label="メッセージへのリアクション"><button type="button" className="reaction-add" aria-label={expanded?'絵文字選択を閉じる':'絵文字リアクションを選ぶ'} aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><SmilePlus size={16}/></button><div className="reaction-summary" inert={expanded}>{buttons.filter(r=>r.count>0).map(({emoji,count,mine})=><button type="button" className="reaction-chip" key={emoji} aria-pressed={mine} aria-label={`${emoji} ${count}件・${mine?'取り消す':'追加する'}`} disabled={disabled||busy||(full&&!mine)} onClick={()=>void react(emoji)}><span>{emoji}</span><b>{count}</b></button>)}{reactions.length>0&&<small className="reaction-limit">{reactions.length}/5</small>}</div>{expanded&&<div className="reaction-picker" role="group" aria-label="絵文字を選択（合計5個まで）" title={full?'合計5個まで。自分のリアクションは取り消せます。':'1メッセージにつき合計5個まで'}>{buttons.map(({emoji,mine})=><button type="button" key={emoji} aria-label={`${emoji}を${mine?'取り消す':'追加する'}`} aria-pressed={mine} disabled={disabled||busy||(full&&!mine)} onClick={()=>void react(emoji)}>{emoji}</button>)}</div>}</div>{error&&<span className="reaction-error" role="alert">{error}</span>}</div>
}
