'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {Volume2,VolumeX} from 'lucide-react';
import {Room,judge} from '@/lib/game';
const positions:Record<number,number[]>={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
export function Dice({value,small=false}:{value:number;small?:boolean}){return <span className={`die ${small?'small':''} ${value===1?'one':''}`} role="img" aria-label={`${value}の目`}>{Array.from({length:9},(_,i)=><i key={i} className={(positions[value]||[]).includes(i)?'pip':'blank'}/>)}</span>}
// Three stable slots are reused for every throw; previous throws never add nodes.
export function DiceTray({values,rolling}:{values:number[];rolling:boolean}){
 return <div className={`dice-row ${values.length===0?'arena-empty':''}`} data-state={rolling?'rolling':values.length?'revealing':'empty'} aria-label={values.length===0?'サイコロは片付けられています':undefined}>{[0,1,2].map(i=><div className="die-flight" style={{'--die-index':i} as CSSProperties} key={i}>{values[i]>=1&&values[i]<=6?<Dice value={values[i]}/>:<span className="empty-die-slot" aria-hidden="true"/>}</div>)}</div>
}
type Reveal={key:string;scope:string;name:string;player:string;dice:number[];rank:number;multiple:number;delta?:number};
function CountUp({value}:{value:number}){const [n,setN]=useState(0);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setN(value);return}let frame=0;const start=performance.now();const tick=(t:number)=>{const p=Math.min(1,(t-start)/950);setN(Math.round(value*(1-Math.pow(1-p,3))));if(p<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value]);return <>{n>0?'+':''}{n.toLocaleString()}</>}
export default function TableEffects({room,meId,rolling}:{room:Room|null;meId?:string;rolling:boolean}){
 const [sound,setSound]=useState(true),[reveal,setReveal]=useState<Reveal|null>(null),[tumble,setTumble]=useState([2,5,3]);
 const audio=useRef<AudioContext|null>(null),soundRef=useRef(true),previous=useRef<Room|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function tone(freq:number,delay=0,length=.12,type:OscillatorType='sine',volume=.06){const ctx=audio.current;if(!soundRef.current||!ctx||ctx.state!=='running')return;const osc=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(freq,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.01);gain.gain.exponentialRampToValueAtTime(.0001,start+length);osc.connect(gain);gain.connect(ctx.destination);osc.start(start);osc.stop(start+length+.02);osc.onended=()=>{osc.disconnect();gain.disconnect()}}
 async function toggleSound(){if(soundRef.current){soundRef.current=false;setSound(false);await audio.current?.suspend();return}try{audio.current??=new AudioContext();await audio.current.resume();soundRef.current=true;setSound(true);tone(660,0,.1)}catch{soundRef.current=false;setSound(false)}}
 useEffect(()=>{
  const unlock=()=>{if(!soundRef.current)return;try{if(!audio.current||audio.current.state==='closed')audio.current=new AudioContext();if(audio.current.state!=='running')void audio.current.resume().catch(()=>{});}catch{}};
  document.addEventListener('pointerup',unlock,true);document.addEventListener('keydown',unlock,true);
  return()=>{document.removeEventListener('pointerup',unlock,true);document.removeEventListener('keydown',unlock,true)};
 },[]);
 useEffect(()=>{if(!rolling)return;setReveal(null);if(timer.current)clearTimeout(timer.current);if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;let i=0;const t=setInterval(()=>{setTumble([1+i%6,1+(i+2)%6,1+(i+4)%6]);tone(170+(i%3)*65,0,.045,'triangle',.035);i++},85);return()=>clearInterval(t)},[rolling]);
 useEffect(()=>{if(rolling)return;const before=previous.current;previous.current=room;if(!room||!before||before.code!==room.code||before.round!==room.round||room.phase==='lobby'||room.phase==='betting'){if(timer.current)clearTimeout(timer.current);timer.current=null;setReveal(null);return}const changed=room.players.find(p=>p.rolls>(before.players.find(q=>q.id===p.id)?.rolls??p.rolls));const settled=room.phase==='result'&&before.phase!=='result';if(!changed&&!settled){if(before.turn!==room.turn||before.phase!==room.phase){if(timer.current)clearTimeout(timer.current);timer.current=null;setReveal(null)}return;}const who=changed||room.players.find(p=>p.id===meId);if(!who?.dice.length)return;const role=judge(who.dice),delta=settled?room.players.find(p=>p.id===meId)?.delta:undefined;const event={scope:`${room.code}:${room.round}:${room.phase}`,key:`${room.round}-${who.id}-${who.rolls}-${room.phase}`,name:role.name,rank:role.rank,multiple:role.multiple,player:who.name,dice:who.dice,delta};setReveal(event);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{timer.current=null;setReveal(null)},settled?3100:role.rank>=8?2400:1600);
 tone(100,0,.18,'triangle',.1);tone(190,.06,.08,'triangle',.06);
 if(delta!==undefined&&delta>0){[523,659,784,1047,1319].forEach((f,i)=>tone(f,.2+i*.1,.4,'sine',.06))}else if(role.rank>=8){[523,659,784,1047].slice(0,role.rank===10?4:3).forEach((f,i)=>tone(f,.18+i*.11,.32,'sine',.055))}else if(role.rank===-1){tone(220,.15,.2,'triangle');tone(130,.3,.25,'triangle')}else if(role.rank>0)tone(580,.17,.18);
 },[room,meId,rolling]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);void audio.current?.close()},[]);
 const activeReveal=!rolling&&room&&reveal?.scope===`${room.code}:${room.round}:${room.phase}`?reveal:null;
 // Only the current reveal is shown. Saved dice are used for scoring, not history.
 const values=rolling?tumble:activeReveal?.dice??(room?[]:[1,4,6]);
 const big=!!activeReveal&&(activeReveal.rank>=8||(activeReveal.delta??0)>0);const jackpot=activeReveal?.rank===10;const bad=activeReveal?.rank===-1;
 return <><button className="sound-toggle" onClick={toggleSound} aria-pressed={sound} aria-label={sound?'効果音をオフ':'効果音をオン'}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}音 {sound?'ON':'OFF'}</button><div className={`juice-stage ${rolling?'is-tumbling':''} ${activeReveal?'has-landed':''} ${big?'gold-hit':''}`}>{activeReveal&&<span className="impact-ring" aria-hidden="true"/>}<DiceTray values={values} rolling={rolling}/>{rolling&&<div className="roll-cue">勝負…！</div>}</div>
 {activeReveal&&<div key={activeReveal.key} className={`role-reveal ${big?'big-hit':''} ${jackpot?'pinnacle':''} ${bad?'bad-hit':''}`} role="status" aria-live="polite"><div className="reveal-content"><span className="reveal-player">{activeReveal.player} の出目</span><strong className="reveal-name">{activeReveal.name}</strong>{activeReveal.rank>=8?<span className="reveal-multiplier">×{activeReveal.multiple}<small>倍役</small></span>:<span className="reveal-caption">{bad?'ヒフミ！':activeReveal.rank===0?'役なし': '出目確定'}</span>}{activeReveal.delta!==undefined&&<div className={`payout ${activeReveal.delta>0?'won':activeReveal.delta<0?'lost':''}`}><span>{activeReveal.delta>0?'YOU WIN':activeReveal.delta<0?'YOU LOSE':'DRAW'}</span><b><CountUp value={activeReveal.delta}/><small> CHIPS</small></b></div>}</div>{big&&<div className="chip-burst" aria-hidden="true">{Array.from({length:24},(_,i)=><i key={i} style={{'--x':`${((i*73)%360)-180}px`,'--y':`${-70-((i*47)%210)}px`,'--spin':`${i*67}deg`,'--delay':`${(i%6)*.045}s`} as CSSProperties}>{i%3===0?'✦':'●'}</i>)}</div>}</div>}</>
}
